Возможность изменять порты ответа через аргументы командной строки
go-park-mail-ru/2021_1_Execute pull request #12
Opened 2021-03-19 08:01 UTC by ZhukDima

2021-03-19 11:07 UTC, ZhukDima commented
![](https://github.trello.services/images/mini-trello-icon.png) [Научить лить на тачку для теста пул-реквеста](https://trello.com/c/5d1XSgkk/34-%D0%BD%D0%B0%D1%83%D1%87%D0%B8%D1%82%D1%8C-%D0%BB%D0%B8%D1%82%D1%8C-%D0%BD%D0%B0-%D1%82%D0%B0%D1%87%D0%BA%D1%83-%D0%B4%D0%BB%D1%8F-%D1%82%D0%B5%D1%81%D1%82%D0%B0-%D0%BF%D1%83%D0%BB-%D1%80%D0%B5%D0%BA%D0%B2%D0%B5%D1%81%D1%82%D0%B0)

2021-03-20 06:57 UTC, MKondakova requested changes

2021-03-20 06:57 UTC, MKondakova commented on server.go
> +	clintPort := flag.Int("clint-port", 3000, "")
поясни за clint

2021-03-20 09:02 UTC, MKondakova approved these changes

2021-03-26 11:10 UTC, merged