Пререорганизация архитектуры
go-park-mail-ru/2021_1_Execute pull request #15
Opened 2021-04-10 00:10 UTC by MKondakova

Пока есть проблема с кастомными валидаторами. Файлы базы данных отсутствуют, так как уже готовы файлы в соседней ветке, они реализованы согласно интерфейсам и архитектуре. Для проверки работоспособности необходимо слияние двух веток в третью.

2021-04-10 23:53 UTC, MKondakova commented
Для проверки работоспособности использовать ветку [db+architecture](https://github.com/go-park-mail-ru/2021_1_Execute/tree/db%2Barchitecture)

2021-04-10 23:57 UTC, MKondakova commented
![](https://github.trello.services/images/mini-trello-icon.png) [Переписать бэк на модули](https://trello.com/c/07l2wMoK/43-%D0%BF%D0%B5%D1%80%D0%B5%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D0%B1%D1%8D%D0%BA-%D0%BD%D0%B0-%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D0%B8)

2021-04-11 16:48 UTC, AlexisOMG requested changes

2021-04-11 16:48 UTC, AlexisOMG commented on app/server.go
> +	DBUri := "postgresql://postgres:123456@localhost:5432/trello"
Давай добавим такую же настройку через параметры, как и для портов

2021-04-11 16:48 UTC, AlexisOMG commented on app/server.go
> +	_, err = pool.Exec(ctx, initComands)
Уверена, что за это должен отвечать сервер?

2021-04-11 16:48 UTC, AlexisOMG commented on internal/users/delivery/http/data_validation.go
> +func init() {
Желательно добавить валидацию всех данных, которые в дальнейшем попадут в sql запрос

2021-04-11 19:09 UTC, MKondakova commented on internal/users/delivery/http/data_validation.go
> +func init() {
это все оставшиеся данные

2021-04-12 19:05 UTC, keithzetterstrom commented on internal/users/delivery/http/login_and_registration_handler.go
> +type UserLoginRequest struct {
структуры, которые являются моделями, используются для передачи/хранения данных стоит вынести в отдельный пакет

2021-04-12 19:05 UTC, keithzetterstrom commented on internal/domain/session.go
> +type SessionsRepository interface {
понятнее, когда интерфейс находится ближе к реализации, то есть папка `session`, в ней: `session/repository`, `session/delivery`, `session/usecase` и `session/session.go`,  в котором объявлены эти интерфейсы

2021-04-12 19:12 UTC, keithzetterstrom commented
желательно определиться с названием файлов, у вас в некоторых местах через _, в некоторых с большими буквами

2021-04-20 11:00 UTC, closed without merging